# Generated by Django 5.0.3 on 2024-03-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Корзина создана'), (2, 'Пустая'), (3, 'Не звершена'), (4, 'Наполнена'), (5, 'Оплаченная')], default=1, verbose_name='Корзина'),
        ),
    ]
