# Generated by Django 5.0.3 on 2024-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv_code',
            field=models.CharField(default=None, max_length=3, verbose_name='CVV-код'),
        ),
        migrations.AddField(
            model_name='card',
            name='first_name_card',
            field=models.CharField(default=None, max_length=25, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='card',
            name='last_name_card',
            field=models.CharField(default=None, max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_card',
            field=models.IntegerField(default=None, max_length=16, verbose_name='Номер Карты'),
        ),
    ]
