# Generated by Django 5.0.3 on 2024-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/courier', verbose_name='Аватар'),
        ),
    ]
