# Generated by Django 5.0.3 on 2024-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Заказ создан'), (2, 'Заказ принят'), (3, 'Заказ доставлен'), (4, 'Заказ завершен'), (5, 'Заказ отменен')], default=1, verbose_name='статус'),
        ),
    ]
