# Generated by Django 5.0.3 on 2024-04-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_method',
            old_name='payment_method',
            new_name='payment_methods',
        ),
    ]
