# Generated by Django 5.0.3 on 2024-04-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_paymentmethod_alter_payment_method_payment_methods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
