# Generated by Django 5.0.3 on 2024-04-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_delivery_delivery_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_orders',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
