# Generated by Django 5.0.3 on 2024-04-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_review_orders_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_orders',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
    ]
