# Generated by Django 5.0.3 on 2024-04-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_review_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_orders',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='review_orders',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review_orders',
            name='text',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
    ]
